-- CREATE DATABASE VITALS;

CREATE TABLE PATIENTS (
    PATIENT_ID BIGINT PRIMARY KEY NOT NULL,
    REGISTRATION_DATE DATE NOT NULL DEFAULT GETDATE(),
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER NVARCHAR(10) NOT NULL,
    AGE SMALLINT NOT NULL, 
    BLOOD_TYPE NVARCHAR(5) NOT NULL
);

CREATE TABLE MEDICAL_ROL(
    ROLE_ID TINYINT PRIMARY KEY NOT NULL,
    ROLE_NAME NVARCHAR(100) NOT NULL
);

CREATE TABLE MEDICAL_STAFF (
    STAFF_ID BIGINT PRIMARY KEY NOT NULL,
    ROLE_ID TINYINT NOT NULL,
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL CHECK (EMAIL LIKE '%_@__%.__%'),
    CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES MEDICAL_ROL(ROLE_ID)    
);

CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    STAFF_ID BIGINT NOT NULL,
    PATIENT_ID BIGINT NOT NULL,
    DATE_ASSIGNED DATE NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_PATIENT_ID FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
    CONSTRAINT FK_STAFF_ID FOREIGN KEY (STAFF_ID) REFERENCES MEDICAL_STAFF(STAFF_ID)
);

CREATE TABLE VITAL (
    VITAL_ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ASSIGNMENT_ID UNIQUEIDENTIFIER NOT NULL,
    DATA_CREATED DATETIME NOT NULL DEFAULT GETDATE(),
    HEART_RATE SMALLINT NOT NULL,
    SATURATION SMALLINT NOT NULL,
    RESPIRATORY_RATE SMALLINT NOT NULL,
    TEMPERATURE SMALLINT NOT NULL,
    BLOOD_GLUCOSE SMALLINT NOT NULL,
    BLOOD_PRESSURE NVARCHAR(10) NOT NULL,
    NOTE_MEDICAL NVARCHAR(255) NOT NULL,
    CONSTRAINT FK_ASSIGNMENT_ID FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ASSIGNMENT_ID)
)