-- Preview Consult
SELECT 
    a.ASSIGNMENT_ID,
    mr.ROLE_NAME,
	a.STAFF_ID,
    CONCAT(ms.FIRST_NAME, ' ' ,ms.LAST_NAME) as STAFF_NAME,
    a.PATIENT_ID,
	CONCAT(p.FIRST_NAME, ' ', p.LAST_NAME) as PATIENT_NAME
FROM 
	MEDICAL_STAFF ms
JOIN
	MEDICAL_ROL mr ON ms.ROLE_ID = mr.ROLE_ID
JOIN
	ASSIGNMENT a ON ms.STAFF_ID = a.STAFF_ID
JOIN 
	PATIENTS p ON a.PATIENT_ID =p.PATIENT_ID

-- Create View
-- View to show all assignments
CREATE VIEW ALL_ASSIGNMENT AS
SELECT 
    a.ASSIGNMENT_ID,
    mr.ROLE_NAME,
	a.STAFF_ID,
    CONCAT(ms.FIRST_NAME, ' ' ,ms.LAST_NAME) as STAFF_NAME,
    a.PATIENT_ID,
	CONCAT(p.FIRST_NAME, ' ', p.LAST_NAME) as PATIENT_NAME
FROM 
	MEDICAL_STAFF ms
JOIN
	MEDICAL_ROL mr ON ms.ROLE_ID = mr.ROLE_ID
JOIN
	ASSIGNMENT a ON ms.STAFF_ID = a.STAFF_ID
JOIN 
	PATIENTS p ON a.PATIENT_ID =p.PATIENT_ID

-- Call View
SELECT * FROM ALL_ASSIGNMENT
