SELECT 
    a.ASSIGNMENT_ID,
    mr.ROLE_NAME,
	a.STAFF_ID,
    ms.FIRST_NAME,
    ms.LAST_NAME,
    a.PATIENT_ID,
	p.FIRST_NAME,
    p.LAST_NAME,
    v.DATA_CREATED,
    v.HEART_RATE as LPM,
    v.SATURATION as SpO2,
    v.RESPIRATORY_RATE as RPM,
    v.TEMPERATURE as C,
    v.BLOOD_GLUCOSE as mg_dL,
    v.BLOOD_PRESSURE as mmHg,
    v.NOTE_MEDICAL as NOTE
FROM 
	MEDICAL_STAFF ms
JOIN
	MEDICAL_ROL mr ON ms.ROLE_ID = mr.ROLE_ID
JOIN
	ASSIGNMENT a ON ms.STAFF_ID = a.STAFF_ID
JOIN 
	PATIENTS p ON a.PATIENT_ID =p.PATIENT_ID
JOIN 
    VITAL v ON a.ASSIGNMENT_ID = v.ASSIGNMENT_ID
WHERE 
    a.PATIENT_ID = @PATIENT_ID
